### ISSUE TITLE
Flathub data-checker

### ISSUE THREAD

**Issue by farribeiro** [flathub/br.gov.fazenda.receita.irpf#4]
Can you use flathub data checker instead of own data checker for the app and the resources?

The bot update the link and sha256 sum, open a PR... Have some ways to check new versions

The link to project: https://github.com/flathub/flatpak-external-data-checker

**Comment by guihkx** [comment]
Although I'm already using nvchecker to check for IRPF updates, I agree that the data-checker is very useful, so I added it for the main program.

However, I'm afraid it won't be of any use for the XML modules, mostly because they're too dynamic. Which means that we have no control over what .ZIP files are added or removed [here](https://downloadirpf.receita.fazenda.gov.br/irpf/2022/irpf/update/latest.xml).

**Comment by guihkx** [comment]
Actually, thinking more about it, I could add the data-checker for all ZIP modules already in the manifest, but newer ones still must be added through the `tools/update-zip-assets.py` script.

**Comment by farribeiro** [comment]
Great to apply the ideia
